apiVersion: backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "federations-ec2-teste-2"
  environment:
    cluster_type: ec2
  annotations:
    github.com/project-slug: veecode-homolog/federations-ec2-teste-2
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: terraform-deploy.yml,terraform-destroy.yml
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
  
